// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp8rbCRw1D9rBMkA1Bkmybdm2tZQJDm68',
    appId: '1:381872173981:web:7f2d7a27718abc80927574',
    messagingSenderId: '381872173981',
    projectId: 'hero-878d8',
    authDomain: 'hero-878d8.firebaseapp.com',
    storageBucket: 'hero-878d8.appspot.com',
    measurementId: 'G-TEJKBNR7BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoCmLvBGaAdbv_Z_ULO1tpqJplKMvr8C0',
    appId: '1:381872173981:android:486322d9cd284f4b927574',
    messagingSenderId: '381872173981',
    projectId: 'hero-878d8',
    storageBucket: 'hero-878d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_fSi5oQeYH_osZvUVBFWFziF4J6r4s8',
    appId: '1:381872173981:ios:bf04abcb37b860c7927574',
    messagingSenderId: '381872173981',
    projectId: 'hero-878d8',
    storageBucket: 'hero-878d8.appspot.com',
    iosBundleId: 'com.topbusiness.hero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg_fSi5oQeYH_osZvUVBFWFziF4J6r4s8',
    appId: '1:381872173981:ios:8d965835c72ff7b1927574',
    messagingSenderId: '381872173981',
    projectId: 'hero-878d8',
    storageBucket: 'hero-878d8.appspot.com',
    iosBundleId: 'com.topbusiness.hero.RunnerTests',
  );
}
